### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by blimeybloke** [NNTmux/newznab-tmux#144] opened 2017-06-17 00:42 UTC
Ok, after 2 days, finally have things where I can access them.  Only error 500 I see is when I try to view a releases data but other than that, no more error 500.

I am running 0.x

After everything I run, I get a Segmentation fault (core dumped) error.  It kills the shell script for updating due to the error.

Was this fixed in Dev or is it something else?

Here is a log snippet from kern.log:

Jun 16 20:17:35 Ubuntu-1404-trusty-64-minimal kernel: [ 4632.724487] php[10030]: segfault at a00000001 ip 00005636558f3259 sp 00007ffca3a96c18 error 6 in php7.1[5636556a0000+3b9000]
Jun 16 20:17:46 Ubuntu-1404-trusty-64-minimal kernel: [ 4642.981407] php7.1[10037]: segfault at a00000001 ip 000055aff3570259 sp 00007ffe5aa991c8 error 6 in php7.1[55aff331d000+3b9000]
Jun 16 20:17:46 Ubuntu-1404-trusty-64-minimal kernel: [ 4643.051779] php[10035]: segfault at a00000001 ip 000055a8fa62d259 sp 00007fff7436ca98 error 6 in php7.1[55a8fa3da000+3b9000]
Jun 16 20:17:46 Ubuntu-1404-trusty-64-minimal kernel: [ 4643.317906] php7.1[10056]: segfault at a00000001 ip 000056297533c259 sp 00007ffc7146f058 error 6 in php7.1[5629750e9000+3b9000]
Jun 16 20:17:46 Ubuntu-1404-trusty-64-minimal kernel: [ 4643.388052] php[10054]: segfault at a00000001 ip 000055a8fa62d259 sp 00007fff7436ca98 error 6 in php7.1[55a8fa3da000+3b9000]
Jun 16 20:17:46 Ubuntu-1404-trusty-64-minimal kernel: [ 4643.757381] php7.1[10074]: segfault at a00000001 ip 000055c80080f259 sp 00007ffc8c3d76a8 error 6 in php7.1[55c8005bc000+3b9000]
Jun 16 20:17:46 Ubuntu-1404-trusty-64-minimal kernel: [ 4643.826338] php[10032]: segfault at a00000001 ip 000055a8fa62d259 sp 00007fff7436ca98 error 6 in php7.1[55a8fa3da000+3b9000]

Seems to happen after every script I run.

Running 7.1

**Comment by nightah** [comment] 2017-06-17 01:51
Fairly certain the segfaults on the scripts isn't an actual problem, just an annoyance.
I get exactly the same problem, I recall Darius mentioning that it was fixed in php7.1.3 or something but it still seems to occur for me despite having a newer version than that.

I had a similar problem with http 500 errors when trying to view a release too, I thought it had to do with changing to a remote db setup. I'll try a local db setup again today just to ensure that isn't an actual problem.

**Comment by blimeybloke** [comment] 2017-06-17 01:53
Thanks, please let me know.  As for the segfaults, the main issue is when running in a screen script, it will abort the script everytime it hits a segfault

**Comment by nightah** [comment] 2017-06-17 02:00
The segfaults always happen at the end of the script though right?
I guess the reason this isn't really a problem for tmux is because tmux spawns a new script after the respective sleep timers etc.

Either way if my memory serves me correctly the segfault issue is a php issue and not related to nntmux or the php scripts. Have you tried running tmux as opposed to screen?

**Comment by blimeybloke** [comment] 2017-06-17 02:01
No, I could give that a shot. I  just have my own order of scripts for backfilling. I will give that a shot next.

**Comment by nightah** [comment] 2017-06-17 02:06
Fairly certain most of the nntmux community are also running tmux.
Darius could probably comment better than I could here, however, tmux is probably what receives the most testing etc. That's not to say that screen isn't supported, just that it could be lacking a little behind where tmux currently is.

**Comment by nightah** [comment] 2017-06-17 10:22
Okay confirmed that if you're not seeing releases and getting http 500 errors it's likely a setup issue, unless something was changed between Darius' commits today.

I just did a fresh install and am able to view releases, so whatever issue I had earlier was likely to do with my remote db setup.

Perhaps try another fresh install, if you still have issues I can try help you out on IRC sometime.

**Comment by DariusIII** [comment] 2017-06-17 10:31
You need to do 2 things:
 - Enable debugging in nntmux/config/settings.php
 - Check your apache/nginf error logs located in /var/log/
 - Check resources/logs/php_errors_cli.log and php_errors_web.log

That is how we can help and fix potential bugs.

**Comment by blimeybloke** [comment] 2017-06-17 13:09
Nightah,
I will do another fresh install.  May I ask which guide you are using, the normal one? Are you running Ubuntu 14.x and finally, are you doing dev or stable build?
TIA

Darius,
I will enable that for next build if it still acts up and either way report back.   It will be a few days till I get the time to go through the set up again, so probably around Tuesday or Weds.

**Comment by nightah** [comment] 2017-06-17 13:20
The normal guide is what I used however because I don't use apache and I use nginx a couple other extra steps.
I use dev also I haven't used 0.x.

**Comment by blimeybloke** [comment] 2017-06-20 23:41
Finally getting around to redo this, still have 1 open question before I start on my desert walk :)  Are you using Ubuntu 14 or 16?  TIA

**Comment by nightah** [comment] 2017-06-21 05:22
I was using 16.04 for my Ubuntu build. There were some small nuances to overcome with the build, however, nothing too difficult.

I personally prefer running on Arch because it's bleeding edge and most packages are in line with upstream. @DariusIII has moved to only supporting php7.1 etc.

Honestly if you have a preferred distribution that you have experience with, stick to it. As long as you meet all the minimum version requirements. Linux is Linux.

**Comment by DariusIII** [comment] 2017-06-21 07:25
Some segfaults are caused by lithium, as far as i see. Tmux update using lithium causes segfaults on end, while same using laravel/symfony does not. Unfortunately, i had to revert that code as it was causing issues in other scripts.

**Comment by blimeybloke** [comment] 2017-06-21 11:24
I just installed 14.04 since that is what the guide calls for.  Will start the build process and mention anything I see in hopes of updating the install guide.

**Comment by DariusIII** [comment] 2017-06-21 12:10
I have updated the wiki. Hope that solves some of your issues.

**Comment by blimeybloke** [comment] 2017-06-21 18:54
Hoping the following will help, couple changes I am seeing so far in the install guide and I am using ubuntu 14.04

typo:
dpkg-i php7.1-yenc_1.3.0_amd64.deb  should be  dpkg -i php7.1-yenc_1.3.0_amd64.deb

The default directions in ubuntu 14.x will install mariadb 5.5 but that will fail later on as 5.6 is required.


In the Install Composer area, this is what I am doing but its not documented and maybe I am doing something wrong to install composer:
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r 'if (hash_file("SHA384", "composer-setup.php") === preg_filter("#^.*?<pre>|</pre>.*$#s", "", file_get_contents("https://composer.github.io/pubkeys.html"))) { echo "Installer verified"; } else { echo "Installer corrupt"; unlink("composer-setup.php"); } echo PHP_EOL;'
sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer


but I am up and running using tmux

**Comment by blimeybloke** [comment] 2017-06-22 00:45
Another question/mod for docs:  What do I put in the yenc type?

I used php7.1-yenc_1.3.0_amd64.deb during the install but am not sure what I should put in that text box in the admin area.  Do I leave it blank or put yenc?

php -m | grep yenc
yenc

**Comment by nightah** [comment] 2017-06-22 01:02
You leave it blank if using php-yenc.

**Comment by blimeybloke** [comment] 2017-06-22 01:57
thanks,  I just noticed my notes for composer are broke, trying again:
`
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r 'if (hash_file("SHA384", "composer-setup.php") === preg_filter("#^.*?<pre>|</pre>.*$#s", "", file_get_contents("https://composer.github.io/pubkeys.html"))) { echo "Installer verified"; } else { echo "Installer corrupt"; unlink("composer-setup.php"); } echo PHP_EOL;'
sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer

`

**Comment by blimeybloke** [comment] 2017-06-23 02:27
Strange, I just noticed:
Backfilling: 1 group(s) - Using compression? No

**Comment by nightah** [comment] 2017-06-23 02:42
What's strange about that?
Do you have compression turned on but backfilling says it's not using it?

I would also suggest that if there's a suspected issue, that you log a new issue with a problem statement along with any logs/configuration which could help towards fixing the issue you describe.

**Comment by blimeybloke** [comment] 2017-06-23 04:12
Its odd because I mentioned installing yenc.  php7.1-yenc_1.3.0_amd64.deb

Sorry tapping this out on mobile.

**Comment by nightah** [comment] 2017-06-23 05:03
I don't understand, do you think php-yenc has to do with compression of articles?
Not entirely sure where you're drawing a connection between the two.

**Closed** 2017-06-23 06:22 UTC
