### ISSUE TITLE
No release fresh install

### ISSUE THREAD

**Issue by blimeybloke** [NNTmux/newznab-tmux#728] opened 2018-09-21 12:10 UTC
So close, hopefully this is last issue but again, having some serious fun.
So I am now at step 12, which has a typo in the install guide:

It says:
Move to the indexing script location in your terminal:
cd /var/www/NNTmux/misc/update/nix/multiprocessing

It should be:
/var/www/NNTmux/misc/update/multiprocessing

When I run php binaries.php 0 it finds no parts for any group.  I am testing with a.b.teevee and 3 others to be sure.  I have even tried php binaries.php 1000000 and still 0 parts.

Cheers again Darius for all your help, hopefully my issues will help others.

**Comment by DariusIII** [comment] 2018-09-21 12:17
It will not find any new parts because update_groups script that populates the shortgroups table is not run.

Best way is to fire up tmux, as that script runs there.

**Comment by blimeybloke** [comment] 2018-09-21 12:18
Same issue when I run in tmux too. :)  It just hits all 4 groups and says waiting for the delay to scan again.

**Comment by DariusIII** [comment] 2018-09-21 12:19
Can i have a screenshot, please?

**Comment by blimeybloke** [comment] 2018-09-21 12:27
yes, its enabled.  
<img width="754" alt="mgr" src="https://user-images.githubusercontent.com/20652035/45881101-2a683e00-bd78-11e8-8580-4efece43da82.png">

**Comment by blimeybloke** [comment] 2018-09-21 12:29
Here is new screenshot with 3 groups

<img width="1769" alt="tmux2" src="https://user-images.githubusercontent.com/20652035/45881158-597eaf80-bd78-11e8-923d-b99f4523db84.png">

**Comment by DariusIII** [comment] 2018-09-21 12:30
Is that simple threaded?

**Comment by blimeybloke** [comment] 2018-09-21 12:31
yes

**Comment by DariusIII** [comment] 2018-09-21 12:32
Switch to full threaded.

**Comment by blimeybloke** [comment] 2018-09-21 12:34
on full threaded, more happens but nothing in the parts table.  And a strange undefined offset: 0 with each group.

<img width="995" alt="tmux3" src="https://user-images.githubusercontent.com/20652035/45881440-2c7ecc80-bd79-11e8-807f-b918900d9b2c.png">

**Comment by DariusIII** [comment] 2018-09-21 12:48
If the server is not public, please enable debugging and set APP_ENV to local, so more debug info comes out.

**Comment by blimeybloke** [comment] 2018-09-21 12:49
ok, I just rebooted the server so will have an update in 5 minutes.

**Comment by DariusIII** [comment] 2018-09-21 12:50
What version of tmux do you run? Compiled from source by using the included script or bundled with distribution?

**Comment by blimeybloke** [comment] 2018-09-21 12:53
No further data shows with those 2 settings in tmux.  When I do tmux -V I get tmux master
I did follow the guide and did ./install_tmux.sh

I am running ubuntu 16.04 too

**Comment by DariusIII** [comment] 2018-09-21 13:00
That is fine. I am getting undefined offsets too, but i cannot find what does cause them.

Will have to investigate.

**Comment by blimeybloke** [comment] 2018-09-21 13:01
Which table does it add parts to?  The "parts" table?  If so, that is empty.

**Comment by blimeybloke** [comment] 2018-09-21 13:02
I just looked at the groups table and it still shows 0 for last_record

**Comment by DariusIII** [comment] 2018-09-21 13:06
Everything goes into` multigroup_ `tables.

**Comment by blimeybloke** [comment] 2018-09-21 13:07
Thats what I was afraid of too.  That has 0 items in it as well.

**Comment by DariusIII** [comment] 2018-09-21 13:11
Can you enable boneless and etc? Just to see if those get populated at all.

**Comment by blimeybloke** [comment] 2018-09-21 13:15
Sure, here it is, same results.  I do see at the top that is is "updating the short_groups table" for .m.xvix and .tv but those 2 are not active anymore.

<img width="1007" alt="tmux4" src="https://user-images.githubusercontent.com/20652035/45883368-e0cf2180-bd7e-11e8-8eee-b8ca3edfd3a0.png">

**Comment by blimeybloke** [comment] 2018-09-21 13:18
It looks like it is updating short_group though.  Just never getting parts.
<img width="640" alt="short_group" src="https://user-images.githubusercontent.com/20652035/45883507-49b69980-bd7f-11e8-9352-6f3acc7629bd.png">

**Comment by DariusIII** [comment] 2018-09-21 13:26
Are you on 0.x or dev?

**Comment by blimeybloke** [comment] 2018-09-21 13:27
dev

**Comment by DariusIII** [comment] 2018-09-21 13:29
Can you update to latest, like right now?

**Comment by blimeybloke** [comment] 2018-09-21 13:29
sure, what is the command? sorry git is my weak point

**Comment by DariusIII** [comment] 2018-09-21 13:30
`php artisan nntmux:all`

**Comment by blimeybloke** [comment] 2018-09-21 13:31
just ran, running tmux now

**Comment by blimeybloke** [comment] 2018-09-21 13:33
Oh, more error info is showing

<img width="1776" alt="tmux5" src="https://user-images.githubusercontent.com/20652035/45884233-618f1d00-bd81-11e8-9f63-39d12d089097.png">

**Comment by DariusIII** [comment] 2018-09-21 13:43
Update again, i screwed one line i wanted to revert, but i pushed that change too.

**Comment by blimeybloke** [comment] 2018-09-21 13:46
updated and running now and same result.  Attached is the screenshot.  Should I reset the groups or anything else?  shortg_groups is getting updated with the latest but just no parts are incoming.

<img width="1765" alt="tmux6" src="https://user-images.githubusercontent.com/20652035/45884943-268de900-bd83-11e8-87ef-f18e8e517714.png">

**Comment by DariusIII** [comment] 2018-09-21 13:53
I will check those undefined offsets. that started appearing couple of days ago.

**Comment by blimeybloke** [comment] 2018-09-21 13:56
Can I convert back to stable? or would that cause more issues?  Just want to get something starting to import for my mates.

**Comment by DariusIII** [comment] 2018-09-21 13:58
Just switch branches:

` git checkout 0.x`

and update:

`php artisan nntmux:all`

**Comment by blimeybloke** [comment] 2018-09-21 14:02
This is really strange.  I went back to stable, but same issue.  Should I try anything else like resetting the groups or anything?

**Comment by blimeybloke** [comment] 2018-09-21 14:06
And now I am trying to switch back to dev and I get
php artisan nntmux:all

In ProviderRepository.php line 208:
Class 'Messerli90\IGDB\IGDBServiceProvider' not found

**Comment by blimeybloke** [comment] 2018-09-21 18:19
looking more into this, it looks like its updating the shortgroup data and then scanning for new stuff after that last shortgroup data, meaning it should be getting data since last shortgroup data and then updating shortgroup with the lastest ID.  Its also never updating the groups table.

**Comment by DariusIII** [comment] 2018-09-21 20:42
I just reinstalled nntmux on test VM, but cannot reproduce this behaviour, unfortunately. 
Will try and catch the problem ASAP.

**Comment by blimeybloke** [comment] 2018-09-21 20:44
Dang, that is not what I was hoping to read.  What OS did you set it up with.  I will gladly image this and rebuild from scratch again.  I can almost do it blind now 👍

**Comment by DariusIII** [comment] 2018-09-21 20:45
It is an old test VM, Ubuntu 16.04 upgraded to 18.04. I thought that i will see what you have, but no. Not even undefined index ones, which i have on live server.

**Comment by blimeybloke** [comment] 2018-09-21 20:47
I am running 16.04 but willing to try 18 again.   I doubt you needed to but did you follow that guide?

**Comment by DariusIII** [comment] 2018-09-21 20:56
By the guide you reffer the one in nntmux wiki, right?

**Comment by blimeybloke** [comment] 2018-09-21 20:57
yes,  https://github.com/NNTmux/newznab-tmux/wiki/Ubuntu-Install-guide

**Comment by DariusIII** [comment] 2018-09-21 20:59
Is there a way for me to ssh into that server?

**Comment by blimeybloke** [comment] 2018-09-21 21:00
sure,  its currently in the middle of imaging so give me about 15 minutes

**Comment by blimeybloke** [comment] 2018-09-21 21:02
whats the best way I can email you?

**Comment by DariusIII** [comment] 2018-09-21 21:03
Yeah email me: dkrisan [at] gmail dot com

**Comment by blimeybloke** [comment] 2018-09-21 21:05
thanks, just waiting on imaging to be done, its taking longer than expected

**Comment by martijndierckx** [comment] 2018-09-30 11:37
I'm on Ubuntu 18.04, NNTmux 0.x, PHP 7.2, MariaDB 10.3 with the same issue:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/3973630/46257182-d535d600-c4b5-11e8-9651-4df0ee35f699.png">

**Comment by DariusIII** [comment] 2018-09-30 13:00
Have you installed sphinx? Sphinxsearch is now mandatory.

**Comment by DariusIII** [comment] 2018-09-30 23:06
I have pushed a fix for that backfill error. You can check if that fixes your issue with it.

**Comment by DariusIII** [comment] 2018-10-02 06:57
I am closing this issue, if the issue persists, feel free to reopen it.

**Closed by DariusIII** 2018-10-02 06:57 UTC
