### ISSUE TITLE
No new releases

### ISSUE THREAD

**Issue by bert0901** [NNTmux/newznab-tmux#658] opened 2018-07-17 19:15 UTC
Just done a pull from 0.x and no release being generated. Did the pull this morning.

Looking at tmux and no collections being converted, and the parts table just getting larger.

The collections are getting larger.

Is there a SQL script to run to show complete collections?

Many Thanks

**Comment by DariusIII** [comment] 2018-07-17 19:24
Any error in logs? Screenshot of releases pane?

**Comment by bert0901** [comment] 2018-07-17 20:53
No errors at all.

Just all '0'

e.g.

Process Releases -> Attempting to find complete collections.
0 collections were found to be complete. Time: 0 second(s)

Process Releases -> Calculating collection sizes (in bytes).

Process Releases -> Delete collections smaller/larger than minimum size/file count from group/site setting.

Deleted 0 collections:
0 smaller than, 0 bigger than, 0 with less files than site/group settings in: 0 second(s)

Process Releases -> Create releases from complete collections.


0 Releases added and 0 duplicate collections deleted in 0 second(s)

Process Releases -> Create the NZB, delete collections/binaries/parts.

0 NZBs created/Collections deleted in 0 seconds.
Total time: 0 second(s)



Process Releases -> Delete finished collections.

Deleting collections/binaries/parts older than 72 hours.
Finished deleting 0 old collections/binaries/parts in 0 seconds.

Deleting collections that were missed after NZB creation.
Finished deleting 0 collections missed after NZB creation in 0 seconds.
Removed 0 parts/binaries/collection rows in 0 second(s)


Process Releases -> Delete releases smaller/larger than minimum size/file count from group/site setting.
Deleted 0 releases:
0 smaller than, 0 bigger than, 0 with less files than site/groups setting in: 0 second(s)

Process Releases -> Delete old releases and passworded releases.

Removed releases: 0 past retention, 0 passworded, 0 crossposted, 0 from disabled categories, 0 smaller than category settings, 0 from disabled music genres, 0 from misc->other0 from misc->hashed, 0 under 95% completion.

Process Releases -> Categorize releases.
0 second(s)

Multi-processing for releases finished in 0.22966313362122 seconds at Tue, 17 Jul 2018 21:51:06 +0100.

**Comment by DariusIII** [comment] 2018-07-17 21:13
Can you enable debugging in your .env file? Info you provided means almost nothing as it is.

**Comment by bert0901** [comment] 2018-07-18 14:20
It is enabled as on a test server.

That's what I don't understand why no errors. I have some time now to go through each commit to find the one that causes the issue.

**Comment by DariusIII** [comment] 2018-08-27 12:31
I am closing this as no more data was provided. If the issue is still present, feel free to reopen it.

**Closed by DariusIII** 2018-08-27 12:31 UTC

**Comment by bert0901** [comment] 2018-08-31 16:49
Been digging into this today as left it alone for a while.

The group is not being passed to the processing of the release in non multigroup setup

Have 3 test groups enabled. It runs only one and stops.

Any help appreciated.
